apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - service.yaml
  - rtc-service.yaml
  - rtc-endpoints.yaml
  - deployment.yaml
