apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sigma-server
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
    verbs:
      - get
      - patch
