apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigma-web-server
spec:
  selector:
    matchLabels:
      app: sigma-web-server
  template:
    metadata:
      labels:
        app: sigma-web-server
    spec:
      containers:
        - name: sigma-web-server
          image: sigma/sigma-web-server
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
